# Generated by Django 3.1.1 on 2021-03-17 06:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=20)),
                ('subject', models.TextField()),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
